### ISSUE TITLE
Tools do not set the entities model after initialisation 

### ISSUE THREAD

**Issue by ambodi** [Gapminder/vizabi#60]
When you are setting entities *after initialization* like this:
```js
    var newOption = {
        state: {
            entities: {
                show: {
                    dim: "geo",
                    filter: {
                        "geo": ['swe', 'nor'],
                        "geo.category": ["country"]
                    }
                }
            }
        }
    };
    
    myVizabi.setOptions(newOption);
```

Basically tool does not react to it. The problem is happening in ```model.js```'s set function:
```js
//if it's an object, set or create submodel
if (_.isPlainObject(vals)) {
    if (this._data[a] && utils.isModel(this._data[a])) {
        promise = this._data[a].set(vals, silent, block_validation);
    }
    //submodel doesnt exist, create it
    else {
        promise = this._initSubmodel(a, vals);
    }
}
```
The promise is returning ```undefined``` and this will bypass validation and triggering the ```change``` event. 

*NOTE*: I talked to @arthurcamara1 about this, and he tested that the function is not working for arrays which are below the first level of models.

**Comment by arthurcamara1** [comment]
Actually the problem was one line that was changed recently, trying to fix #57: https://github.com/Gapminder/vizabi/commit/16b7f952c6f7ce7e9414610d772005909d282e83#diff-9c7d54c531136cd30fb6c59b05b6de85L110

But still, changing entities in bubble chart is causing problems, but different problems now, related to loading - which should be fixed soon as well.

Thanks

**Comment by angieskazka** [comment]
@arthurcamara1 something is still wrong. when selecting many entities, all is fine. When after that i select fewer entities, the error appears and the layout gets destroyed.

interpolate() complains that items array is empty

![image](https://cloud.githubusercontent.com/assets/3648190/6674148/1f756c20-cc18-11e4-8587-90f58d34aa11.png)

**Comment by angieskazka** [comment]
One more thing to add here @arthurcamara1. I found how to reproduce an error.

Show bubble chart in its default state. All is fine.
Now switch entities to "4 regions"

a "change:entities:show" is called, but at this stage `this.model.marker.label.getItems()` returns old items (201 countries instead of 4 regions)

Consequently, the lex, gdp and population can not be resolved for China, because China is not hooked anymore (every time a different property is throwing error, it's not always lex, which makes me think there is some timing issue lurking)

After the update sequence `this.model.marker.label.getItems()` returns 4 regions, as expected.

**Comment by angieskazka** [comment]
This replaced by #106 now
